:- module(db,[course/5]).
course('CSE 3',"Fluency in Information Technology",exactly(4),"Introduces the concepts and skills necessary to effectively use information technology. Includes basic concepts and some practical skills with computer and networks.",none).
course('CSE 4GS',"Mathematical Beauty in Rome",exactly(4),"Exploration of topics in mathematics and engineering as they relate to classical architecture in Rome, Italy. In depth geometrical analysis and computer modeling of basic structures (arches, vaults, domes), and on-site studies of the Colosseum, Pantheon, Roman Forum, and St. Peter Basilica.",'Math 10A or Math 20A; departmental approval, and corequisite of CSE 6GS.').
course('CSE 6GS',"Mathematical Beauty in Rome Lab",exactly(4),"Companion course to CSE 4GS where theory is applied and lab experiments are carried out n the field\uFFFDin Rome, Italy. For final projects, students will select a complex structure (e.g., the Colosseum, the Pantheon, St. Peter, etc.) to analyze and model, in detail, using computer-based tools.",'Math 10A or Math 20A; departmental approval, and corequisite of CSE 4GS.').
course('CSE 5A',"Introduction to Programming I",exactly(4),"(Formerly CSE 62A) Introduction to algorithms and top-down problem solving. Introduction to the C language, including functions, arrays, and standard libraries. Basic skills for using a PC graphical user interface operating system environment. File maintenance utilities are covered. (A student may not receive credit for CSE 5A after receiving credit for CSE 10 or CSE 11 or CSE 8B or CSE 9B or CSE 62B or CSE 65.)",'A familiarity with high-school level algebra is expected, but this course assumes no prior programming knowledge.').
course('CSE 7',"Introduction to Programming with Matlab",exactly(4),"Fundamentals of computer programming and basic software design covering topics related to variables, functions, and control structures; writing, testing, and debugging programs in Matlab. Examples focus on scientific applications. Recommended preparation: high school algebra and familiarity with the computing milieu. Students with limited computing experience may take CSE 3 for preparation. Students may not take CSE 7 after completing COGS 18. Program or material fee may apply.",none).
course('CSE 8A',"Introduction to Computer Science: Java I",exactly(4),"Introductory course for students interested in computer science. Fundamental concepts of applied computer science using media computation. Exercises in the theory and practice of computer science. Hands-on experience with designing, editing, compiling, and executing programming constructs and applications. CSE 8A is part of a two-course sequence (CSE 8A and CSE 8B) that is equivalent to CSE 11. Students should take CSE 8B to complete this track. Formerly offered as corequisite courses CSE 8A plus 8AL. Students who have taken CSE 8B or CSE 11 may not take CSE 8A. Recommended preparation: No prior programming experience is assumed, but comfort using computers is helpful. Students should consult the CSE Course Placement Advice web page for assistance in choosing which CSE course to take first.",none).
course('CSE 8B',"Introduction to Computer Science: Java II",exactly(4),"Continuation of the Java language. Continuation of programming techniques. More on inheritance. Exception handling. CSE 8B is part of a two-course sequence (CSE 8A and CSE 8B) that is equivalent to CSE 11. Students should consult the CSE Course Placement Advice web page for assistance in choosing which CSE course to take first. Students may not receive credit for CSE 8B and CSE 11.",'CSE 8A.').
course('CSE 11',"Introduction to Computer Science and Object-Oriented Programming: Java",exactly(4),"An accelerated introduction to computer science and programming using the Java language. Basic UNIX. Modularity and abstraction. Documentation, testing and verification techniques. Basic object-oriented programming, including inheritance and dynamic binding. Exception handling. Event-driven programming. Experience with AWT library or other similar library. Students who have completed CSE 8B may not take CSE 11. Students should consult the CSE Course Placement Advice web page for assistance in choosing which CSE course to take first. Recommended preparation: high school algebra and familiarity with computing concepts and a course in a compiled language.",none).
course('CSE 12',"Basic Data Structures and Object-Oriented Design",exactly(4),"Use and implementation of basic data structures including linked lists, stacks, and queues. Use of advanced structures such as binary trees and hash tables. Object-oriented design including interfaces, polymorphism, encapsulation, abstract data types, pre-/post-conditions. Recursion. Uses Java and Java Collections.",'CSE 8B or CSE 11, and concurrent enrollment with CSE 15L.').
course('CSE 15L',"Software Tools and Techniques Laboratory",exactly(2),"Hands-on exploration of software development tools and techniques. Investigation of the scientific process as applied to software development and debugging. Emphasis is on weekly hands-on laboratory experiences, development of laboratory notebooking techniques as applied to software design.",'CSE 8B or CSE 11, and concurrent enrollment with CSE 12.').
course('CSE 20',"Discrete Mathematics",exactly(4),"Basic discrete mathematical structures: sets, relations, functions, sequences, equivalence relations, partial orders, and number systems. Methods of reasoning and proofs: prepositional logic, predicate logic, induction, recursion, and pigeonhole principle. Infinite sets and diagonalization. Basic counting techniques; permutation and combinations. Applications will be given to digital logic design, elementary number theory, design of programs, and proofs of program correctness. Credit not offered for both Math 15A and CSE 20. Equivalent to Math 15A.",'CSE 8A or CSE 8B or CSE 11. CSE 8B or CSE 11 may be taken concurrently with CSE 20/ Math 15A.').
course('CSE 21',"Mathematics for Algorithms and Systems",exactly(4),"This course will provide an introduction to the discrete mathematical tools needed to analyze algorithms and systems. Enumerative combinatorics: basic counting principles, inclusion-exclusion, and generating functions. Matrix notation. Applied discrete probability. Finite automata. Credit not offered for both Math 15B and CSE 21. Equivalent to Math 15B.",'CSE 20 or Math 15A.').
course('CSE 30',"Computer Organization and Systems Programming",exactly(4),"Introduction to organization of modern digital computersnderstanding the various components of a computer and their interrelationships. Study of a specific architecture/machine with emphasis on systems programming in C and Assembly languages in a UNIX environment.",'CSE 12, CSE 15L, or consent of instructor.').
course('CSE 80',"UNIX Lab",exactly(2),"The objective of the course is to help the programmer create a productive UNIX environment. Topics include customizing the shell, file system, shell programming, process management, and UNIX tools.",'CSE 8B or CSE 11.').
course('CSE 86',"C++ for Java Programmers",exactly(2),"Helps the Java programmer to be productive in the C++ programming environment. Topics include the similarities and differences between Java and C++ with special attention to pointers, operator overloading, templates, the STL, the preprocessor, and the C++ Runtime Environment.",'CSE 12 or consent of instructor.').
course('CSE 87',"Freshman Seminar",exactly(1),"The Freshman Seminar Program is designed to provide new students with the opportunity to explore an intellectual topic with a faculty member in a small seminar setting. Freshman Seminars are offered in all campus departments and undergraduate colleges, and topics vary from quarter to quarter. Enrollment is limited to fifteen to twenty students, with preference given to entering freshmen.",none).
course('CSE 90',"Undergraduate Seminar",exactly(1),"A seminar providing an overview of a topic of current research interest to the instructor. The goal is to present a specialized topic in computer science and engineering students. May be taken for credit three times when topics vary.",none).
course('CSE 91',"Perspectives in Computer Science and Engineering",exactly(2),"A seminar format discussion led by CSE faculty on topics in central areas of computer science, concentrating on the relation among them, recent developments, and future directions.",'majors only.').
course('CSE 99',"Independent Study in Computer Science and Engineering",exactly(4),"Independent reading or research by special arrangement with a faculty member.",'lower-division standing. Completion of thirty units at UC San Diego with a UC San Diego GPA of 3.0. Special Studies form required. Department stamp required. Consent of instructor and approval of the department.').
course('CSE 100',"Advanced Data Structures",exactly(4),"High-performance data structures and supporting algorithms. Use and implementation of data structures like (un)balanced trees, graphs, priority queues, and hash tables. Also memory management, pointers, recursion. Theoretical and practical performance analysis, both average case and amortized. Uses C++ and STL. Credit not offered for both Math 176 and CSE 100. Equivalent to Math 176. Recommended preparation: background in C or C++ programming.",'CSE 12, CSE 15L, CSE 21 or Math 15B, and CSE 5A or CSE 30 or ECE 15 or MAE 9.').
course('CSE 101',"Design and Analysis of Algorithms",exactly(4),"Design and analysis of efficient algorithms with emphasis of nonnumerical algorithms such as sorting, searching, pattern matching, and graph and network algorithms. Measuring complexity of algorithms, time and storage. NP-complete problems. Credit not offered for both Math 188 and CSE 101. Equivalent to Math 188.",'CSE 12, CSE 21 or Math 15B, or Math 100A, or Math 103A and CSE 100, or Math 176.').
course('CSE 103',"A Practical Introduction to Probability and Statistics",exactly(4),"Distributions over the real line. Independence, expectation, conditional expectation, mean, variance. Hypothesis testing. Learning classifiers. Distributions over R^n, covariance matrix. Binomial, Poisson distributions. Chernoff bound. Entropy. Compression. Arithmetic coding. Maximal likelihood estimation. Bayesian estimation. CSE 103 is not duplicate credit for ECE 109, Econ 120A, or Math 183.",'Math 20A and Math 20B.').
course('CSE 105',"Theory of Computability",exactly(4),"An introduction to the mathematical theory of computability. Formal languages. Finite automata and regular expression. Push-down automata and context-free languages. Computable or recursive functions: Turing machines, the halting problem. Undecidability. Credit not offered for both Math 166 and CSE 105. Equivalent to Math 166.",'CSE 12, CSE 21 or Math 15B, or Math 100A, or Math 103A.').
course('CSE 107',"Introduction to Modern Cryptography",exactly(4),"Topics include private and public-key cryptography, block ciphers, data encryption, authentication, key distribution and certification, pseudorandom number generators, design and analysis of protocols, zero-knowledge proofs, and advanced protocols. Emphasizes rigorous mathematical approach including formal definitions of security goals and proofs of protocol security.",'CSE 21 or Math 15B, CSE 101 or Math 188, CSE 105 or Math 166.').
course('CSE 110',"Software Engineering",exactly(4),"Introduction to software development and engineering methods, including specification, design, implementation, testing, and process. An emphasis on team development, agile methods, and use of tools such as IDE, version control, and test harnesses. CSE 70 is renumbered to CSE 110: students may not receive credit for both CSE 70 and CSE 110.",'CSE 12, CSE 21, or Math 15B.').
course('CSE 112',"Advanced Software Engineering",exactly(4),"This course will cover software engineering topics associated with large systems development such as requirements and specifications, testing and maintenance, and design. Specific attention will be given to development tools and automated support environments.",'CSE 111.').
course('CSE 118',"Ubiquitous Computing",exactly(4),"Explores emerging opportunities enabled by cheap sensors and networked computing devices. Small research projects will be conducted in teams, culminating in project presentations at the end of the term. Section will cover material relevant to the project, such as research methods, software engineering, teamwork, and project management.",'any course from the following: CSE 131, CSE 132B, Cog Sci 102C, Cog Sci 121, Cog Sci 184, COMT 111B, COMT 115, ECE 111, ECE 118, ECE 191, ECE 192, or ICAM 160B; or consent of instructor.').
course('CSE 120',"Principles of Computer Operating Systems",exactly(4),"Basic functions of operating systems; basic kernel structure, concurrency, memory management, virtual memory, file systems, process scheduling, security and protection.",'CSE 30, and CSE 101 or Math 188, and CSE 70 or CSE 110.').
course('CSE 121',"Operating Systems: Architecture and Implementation",exactly(4),"(Formerly CSE 171B.) Case study of architecture and implementation of a selected modern operating system. In-depth analysis through a detailed study of source code. Topics include process creation, context-switching, memory allocation, synchronization mechanisms, interprocess communication, I/O buffering, device drivers, and file systems.",'CSE 120.').
course('CSE 123',"Computer Networks",exactly(4),"(Renumbered from CSE 123A.) Introduction to concepts, principles, and practice of computer communication networks with examples from existing architectures, protocols, and standards with special emphasis on the Internet protocols. Layering and the OSI model; physical and data link layers; local and wide area networks; datagrams and virtual circuits; routing and congestion control; internetworking. Transport protocols. Credit may not be received for both CSE 123 and ECE 158A, or CSE 123A and CSE 123.",'CSE 120 or consent of instructor. Majors only.').
course('CSE 124',"Networked Services",exactly(4),"(Renumbered from CSE 123B.) The architecture of modern networked services, including data center design, enterprise storage, fault tolerance, and load balancing. Protocol software structuring, the Transmission Control Protocol (TCP), remote procedure calls, protocols for digital audio and video communication, overlay and peer-to-peer systems, secure communication. Credit may not be received for both CSE 124 and ECE 158B. Students may not receive credit for both CSE 123B and CSE 124.",'CSE 120 or consent of instructor.').
course('CSE 125',"Software System Design and Implementation",exactly(4),"Design and implementation of large, complex software systems involving multiple aspects of CSE curriculum. Emphasis is on software system design applied to a single, large group project with close interaction with instructor.",'senior standing with substantial programming experience, and consent of instructor. Department stamp required.').
course('CSE 127',"Introduction to Computer Security",exactly(4),"Topics include basic cryptography, security/threat analysis, access control, auditing, security models, distributed systems security, and theory behind common attack and defense techniques. The class will go over formal models as well as the bits and bytes of security exploits.",'CSE 21 or Math 15B, and CSE 120.').
course('CSE 130',"Programming Languages: Principles and Paradigms",exactly(4),"(Formerly CSE 173.) Introduction to programming languages and paradigms, the components that comprise them, and the principles of language design, all through the analysis and comparison of a variety of languages (e.g., Pascal, Ada, C++, PROLOG, ML.) Will involve programming in most languages studied.",'CSE 12, and CSE 100 or Math 176, CSE 105 or Math 166.').
course('CSE 131',"Compiler Construction",exactly(4),"(Formerly CSE 131B.) Introduction to the compilation of programming languages, practice of lexical and syntactic analysis, symbol tables, syntax-directed translation, type checking, code generation, optimization, interpretation, and compiler structure. (Students may receive repeat credit for CSE 131A and CSE 131B by completing CSE 131.)",'CSE 100 or Math 176, CSE 105 or Math 166, CSE 70 or CSE 110, and CSE 130.').
course('CSE 132A',"Database System Principles",exactly(4),"Basic concepts of databases, including data modeling, relational databases, query languages, optimization, dependencies, schema design, and concurrency control. Exposure to one or several commercial database systems. Advanced topics such as deductive and object-oriented databases, time allowing.",'CSE 100 or Math 176.').
course('CSE 132B',"Database Systems Applications",exactly(4),"Design of databases, transactions, use of trigger facilities and datablades. Performance measuring, organization of index structures.",'CSE 132A or equivalent.').
course('CSE 134B',"Web Client Languages",exactly(4),"Design and implementation of interactive World Wide Web clients using helper applications and plug-ins. The main language covered will be Java.",'CSE 100 or Math 176.').
course('CSE 135',"Server-side Web Applications",exactly(4),"Design and implementation of dynamic web-based applications. Multitier architecture, scripting languages, SQL, XML, session handling, nonbrowser clients, web services, and scalability, security, and usability in the web context. Credit is not offered for both CSE 135 and CSE 134A.",'CSE 100 or Math 176.').
course('CSE 140',"Components and Design Techniques for Digital Systems",exactly(4),"(Formerly CSE 170A) Design of Boolean logic and finite state machines; two-level, multilevel combinational logic design, combinational modules and modular networks, Mealy and Moore machines, analysis and synthesis of canonical forms, sequential modules.",'CSE 20 or Math 15A, and corequisite of CSE 140L.').
course('CSE 140L',"Digital Systems Laboratory",exactly(2),"Implementation with computer-aided design tools for combinational logic minimization and state machine synthesis. Hardware construction of a small digital system.",'CSE 20 or Math 15A; CSE 140 must be taken concurrently.').
course('CSE 141',"Introduction to Computer Architecture",exactly(4),"Introduction to computer architecture. Computer system design. Processor design. Control design. Memory systems.",'CSE 140, CSE 140L, or consent of the instructor. CSE 141L should be taken concurrently.').
course('CSE 141L',"Project in Computer Architecture",exactly(2),"Hands-on computer architecture project aiming to familiarize students with instruction set architecture, and design of process. Control and memory systems.",'CSE 110, CSE 140, CSE 140L, or consent of the instructor. CSE 141 should be taken concurrently.').
course('CSE 143',"Microelectronic System Design",exactly(4),"VSLI process technologies; circuit characterization; logic design styles; clocking strategies; computer-aided design tools; subsystem design; design case studies. System design project from hardware description, logic synthesis, physical layout to design verification.",'CSE 140 or CSE 170A or ECE 81.').
course('CSE 144',"Computer-Aided Design of VLSI Circuits",exactly(4),"Introduction to computer-aided design. Placement, assignment and floor planning techniques. Routing. Symbolic layout and compaction. Module generation and silicon compilation.",'CSE 140 and CSE 140L.').
course('CSE 145',"Embedded System Design Project",exactly(4),"Project class building an embedded computing system. Learn fundamental knowledge of microcontrollers, sensors, and actuators. Introduction to the hardware and software tools to build project in a team environment and end-to-end system building.",'CSE 30.').
course('CSE 148',"Advanced Processor Architecture Design Project",exactly(4),"Students will use hardware description language tools to add advanced architectural features to a basic processor design. These features may include pipelining, superscalar execution, branch prediction, and advanced cache features. Designs will be implemented in programmable logic devices.",'CSE 141, CSE 141L, or consent of instructor.').
course('CSE 150',"Introduction to Artificial Intelligence: Search and Reasoning",exactly(4),"Search algorithms including BFS, DFS, iterative deepening and A*, randomized search algorithms including Walksat, syntax and semantics of first-order logic (FOL), knowledge representation in FOL including reasoning, basic reasoning with probabilities, basic Bayesian learning.",'CSE 100 or Math 176, or consent of instructors.').
course('CSE 151',"Introduction to Artificial Intelligence: Statistical Approaches",exactly(4),"Reasoning with probabilities, reasoning and learning with Bayesian networks, decision making under uncertainty, sequential decision making, statistical learning methods, and reinforcement learning.",'CSE 100 or Math 176, or consent of instructor.').
course('CSE 152',"Introduction to Computer Vision",exactly(4),"The goal of computer vision is to compute scene and object properties from images and video. This introductory course includes feature detection, image segmentation, motion estimation, object recognition, and 3-D shape reconstruction through stereo, photometric stereo, and structure from motion.",'Math 20F, CSE 100 or Math 176, CSE 101 or Math 188.').
course('CSE 153',"Cognitive Modeling",exactly(4),"Construction of computational models that o the same things people do,\uFFFDin terms of perception, categorization, memory, language, action, etc. and typically in a fashion that is plausibly carried out by the neural networks in our brains. The model must fit behavioral, neurophysiological, and/or neuropsychological data. Recommended preparation: background knowledge in computer science, cognitive science, psychology, or neuroscience, and a basic understanding of the most fundamental concepts of differential calculus, linear algebra, and statistics. Computer programming skills may be useful to some students as they conduct their term projects, but such skills are not required.",'CSE 100 or Math 176 or consent of instructor.').
course('CSE 160',"Introduction to Parallel Computing",exactly(4),"Introduction to high performance parallel computing: parallel architecture, algorithms, software, and problem-solving techniques. Areas covered: Flynns\uFFFDtaxonomy, processor-memory organizations, shared and nonshared memory models: message passing and multithreading, data parallelism; speedup, efficiency and Amdahl law, communication and synchronization, isoefficiency and scalability. Assignments given to provide practical experience.",'CSE 100 or Math 176.').
course('CSE 164',"GPU Programming",exactly(4),"Principles and practices of programming graphics processing units (GPUs). GPU architecture and hardware concepts, including memory and threading models. Modern hardware-accelerated graphics pipeline programming. Application of GPU programming to rendering of game graphics, including physical, deferring, and global lighting models. Recommended preparation: Practical Rendering and Computation with Direct3D 11 by Jason Zink, Matt Pettineo, and Jack Hoxley.",'CSE 167.').
course('CSE 165',"3D User Interaction",exactly(4),"This course focuses on design and evaluation of three-dimensional (3D) user interfaces, devices, and interaction techniques. The course consists of lectures, literature reviews, and programming assignments. Students will be expected to create interaction techniques for several different 3D interaction devices. Program or material fee may apply.",'CSE 167.').
course('CSE 166',"Image Processing",exactly(4),"Principles of image formation, analysis, and representation. Image enhancement, restoration, and segmentation; stochastic image models. Filter design, sampling, Fourier and wavelet transforms. Selected applications in computer graphics and machine vision.",'Math 20F, CSE 100 or Math 176.').
course('CSE 167',"Computer Graphics",exactly(4),"Representation and manipulation of pictorial data. Two-dimensional and three-dimensional transformations, curves, surfaces. Projection, illumination, and shading models. Raster and vector graphic I/O devices; retained-mode and immediate-mode graphics software systems and applications. Students may not receive credit for both Math 155A and CSE 167.",'CSE 100 or Math 176.').
course('CSE 168',"Computer Graphics II: Rendering",exactly(4),"Weekly programming assignments that will cover graphics rendering algorithms. During the course the students will learn about ray tracing, geometry, tessellation, acceleration structures, sampling, filtering, shading models, and advanced topics such as global illumination and programmable graphics hardware.",'CSE 167.').
course('CSE 169',"Computer Animation",exactly(4),"Advanced graphics focusing on the programming techniques involved in computer animation. Algorithms and approaches for both character animation and physically based animation. Particular subjects may include skeletons, skinning, key framing, facial animation, inverse kinematics, locomotion, motion capture, video game animation, particle systems, rigid bodies, clothing, and hair. Recommended preparation: An understanding of linear algebra.",'CSE 167 or consent of instructor.').
course('CSE 170',"Introduction to Human-Computer Interaction Design",exactly(4),"Introduces fundamental methods and principles for designing, implementing, and evaluating user interfaces. Topics: user-centered design, rapid prototyping, experimentation, direct manipulation, cognitive principles, visual design, social software, software tools. Learn by doing: Work with a team on a quarter-long design project. Cross-listed with COGS 120. Recommended preparation: Basic familiarity with HTML.",'CSE 11 or CSE 8A or CSE 7.').
course('CSE 181',"Molecular Sequence Analysis",exactly(4),"This course covers the analysis of nucleic acid and protein sequences, with an emphasis on the application of algorithms to biological problems. Topics include sequence alignments, database searching, comparative genomics, and phylogenetic and clustering analyses. Pairwise alignment, multiple alignment, DNS sequencing, scoring functions, fast database search, comparative genomics, clustering, phylogenetic trees, gene finding/DNA statistics.",'CSE 100 or Math 176, CSE 101 or Math 188, BIMM 100 or Chem 114C. Bioinformatics majors only. CSE 181 is cross-listed with BIMM 181 and BENG 181.').
course('CSE 182',"Biological Databases",exactly(4),"This course provides an introduction to the features of biological data, how those data are organized efficiently in databases, and how existing data resources can be utilized to solve a variety of biological problems. Object oriented databases, data modeling and description. Survey of current biological database with respect to above, implementation of a database on a biological topic. Cross-listed with BIMM 182/BENG 182/Chem 182.",'CSE 100 or Math 176. Bioinformatics majors only.').
course('CSE 184',"Computational Molecular Biology",exactly(4),"This advanced course covers the application of machine learning and modeling techniques to biological systems. Topics include gene structure, recognition of DNA and protein sequence patterns, classification, and protein structure prediction. Pattern discovery, Hidden Markov models/support victor machines/neural network/profiles. Protein structure prediction, functional characterization or proteins, functional genomics/proteomics, metabolic pathways/gene networks. Cross-listed with BIMM 184/BENG 184/Chem 184.",'BIMM 181 or BENG 181 or CSE 181, BENG 182 or BIMM 182 or CSE 182 or CHEM 182. Bioinformatics majors only.').
course('CSE 190',"Topics in Computer Science and Engineering",exactly(4),"Topics of special interest in computer science and engineering. Topics may vary from quarter to quarter. May be repeated for credit with the consent of instructor.",'consent of instructor. Department stamp required.').
course('CSE 192',"Senior Seminar in Computer Science and Engineering",exactly(1),"The Senior Seminar Program is designed to allow senior undergraduates to meet with faculty members in a small group setting to explore an intellectual topic in CSE (at the upper-division level). Topics will vary from quarter to quarter. Senior seminars may be taken for credit up to four times, with a change in topic, and permission of the department. Enrollment is limited to twenty students, with preference given to seniors. (P/NP grades only.)",'upper-division standing; department stamp required and consent of instructor.').
course('CSE 195',"Teaching",exactly(4),"Teaching and tutorial assistance in a CSE course under the supervision of the instructor. (P/NP grades only.)",'consent of the department chair. Department stamp required.').
course('CSE 197',"Field Study in Computer Science and Engineering",one_of([4,8,12,16]),"Directed study and research at laboratories away from the campus. (P/NP grades only.)",'consent of the instructor and approval of the department. Department stamp required.').
course('CSE 198',"Directed Group Study",one_of([2,4]),"Computer science and engineering topics whose study involves reading and discussion by a small group of students under the supervision of a faculty member. (P/NP grades only.)",'consent of the instructor. Department stamp required.').
course('CSE 199',"Independent Study for Undergraduates",one_of([2,4]),"Independent reading or research by special arrangement with a faculty member. (P/NP grades only.)",'consent of the instructor. Department stamp required.').
course('CSE 199H',"CSE Honors Thesis Research for Undergraduates",exactly(4),"Undergraduate research for completing an honors project under the supervision of a CSE faculty member. May be taken across multiple quarters. Students should enroll for a letter grade. May be taken for credit three times.",'Admission to the CSE department honors program. Consent of the instructor. Department stamp required.').
course('CSE 200',"Computability and Complexity",exactly(4),"Computability review, including halting problem, decidable sets, r.e. sets, many-one reductions; TIME(t(n)), SPACE(s(n)) and general relations between these classes; L, P, PSPACE, NP; NPompleteness; hierarchy theorems; RP, BPP.",'CSE 105 or equivalent.').
course('CSE 202',"Algorithm Design and Analysis",exactly(4),"The basic techniques for the design and analysis of algorithms. Divide-and-conquer, dynamic programming, data structures, graph search, algebraic problems, randomized algorithms, lower bounds, probabilistic analysis, parallel algorithms.",'CSE 101 or equivalent.').
course('CSE 203A',"Advanced Algorithms",exactly(4),"Modern advances in design and analysis of algorithms. Exact syllabus varies. Topics include approximation, randomized algorithms, probabilistic analysis, heuristics, online algorithms, competitive analysis, models of memory hierarchy, parallel algorithms, number-theoretic algorithms, cryptanalysis, computational geometry, computational biology, network algorithms, VLSI CAD algorithms.",'CSE 202.').
course('CSE 205A',"Logic in Computer Science",exactly(4),"(Formerly CSE 208D) Mathematical logic as a tool in computer science. Propositional logic, resolution, first-order logic, completeness and incompleteness theorems with computational viewpoint, finite model theory, descriptive complexity, logic programming, nonmonotonic reasoning, temporal logic. Applications to databases, automatic theorem proving, program verification, and distributed systems.",'CSE 200 or consent of instructor.').
course('CSE 206A',"Lattice Algorithms and Applications",exactly(4),"(Formerly CSE 207C) Introduction to the algorithmic theory of point lattices (aka algorithmic geometry of numbers), and some of its most important applications in cryptography and cryptanalysis. Topics usually include: LLL basis reduction algorithm, cryptanalysis of broadcast RSA, hardness of approximating lattice problems.",'CSE 202, CSE 200, or concurrent.').
course('CSE 207',"Modern Cryptography",exactly(4),"Private and public key cryptography, introduction to reduction based proofs of security, concrete security, block ciphers, pseudorandom functions and generators, symmetric encryption, asymmetric encryption, computational number theory, RSA and discrete log systems, message authentication, digital signatures, key distribution and key management.",'CSE 202 or consent of instructor.').
course('CSE 208',"Advanced Cryptography",exactly(4),"Zero-knowledge, secure computation, session-key distribution, protocols, electronic payment, one-way functions, trapdoor permutations, pseudorandom bit generators, hardcore bits.",'CSE 202, CSE 200, and CSE 207 or consent of instructor.').
course('CSE 210',"Principles of Software Engineering",exactly(4),"(Formerly CSE 264A.) General principles in modern software engineering. Both theoretical and practical topics are covered. Theoretical topics include proofs of correctness, programming language semantics, and theory of testing. Practical topics include structured programming, modularization techniques, design of languages for reliable programming, and software tools.",'CSE 100, 131A, 120, or consent of instructor.').
course('CSE 211',"Software Testing and Analysis",exactly(4),"Survey of testing and analysis methods. Introduction to advanced topics in area as well as traditional production methods. Topics include inspections and reviews, formal analysis, verification and validation standards, nonstatistical testing, statistical-testing and reliability models, coverage methods, testing and analysis tools, and organization management and planning. Methods special to special development approaches such as object-oriented testing will also be described.",'undergraduate major in computer science or extensive industrial experience.').
course('CSE 216',"Research Topics in Human-Computer Interaction",exactly(4),"Prepares students to conduct original HCI research by reading and discussing seminal and cutting-edge research papers. Topics include design, social software, input techniques, mobile, and ubiquitous computing. Student pairs perform a quarter-long mini research project that leverages campus research efforts. Cross-listed with COGS 230.",none).
course('CSE 218',"Advanced Topics in Software Engineering",exactly(4),"This course will cover a current topic in software engineering in depth. Topics in the past have included software tools, impacts of programming language design, and software system structure. (S/U grades permitted.)",none).
course('CSE 219',"Design at Large",exactly(1),"New societal challenges, cultural values, and technological opportunities are changing designnd vice versa. The seminar explores this increased scale, real-world engagement, and disruptive impact. Invited speakers from UC San Diego and beyond share cutting-edge research on interaction, design, and learning. Cross-listed with COGS 229. (S/U grades only.)",none).
course('CSE 221',"Operating Systems",exactly(4),"Operating system structures, concurrent computation models, scheduling, synchronization mechanisms, address spaces, memory management protection and security, buffering, streams, data-copying reduction techniques, file systems, naming, caching, disk organization, mapped files, remote file systems, case studies of major operating systems.",'CSE 120 and 121, or consent of instructor.').
course('CSE 222A',"Computer Communication Networks",exactly(4),"(Formerly CSE 222.) Computer communication network concepts, protocols, and architectures, with an emphasis on an analysis of algorithms, protocols, and design methodologies. Topics will include layering, error control, flow control, congestion control, switching and routing, quality of service management, mobility, naming, security, and selected contemporary topics.",'CSE 123A or consent of instructor.').
course('CSE 222B',"Internet Algorithmics",exactly(4),"(Formerly CSE 228H.) Techniques for speeding up Internet implementations, including system restructuring, new algorithms, and hardware innovations. Topics include: models for protocols, systems and hardware; efficiency principles; applying these principles to deriving techniques for efficient implementation of common endnode and router functions.",'CSE 123A or CSE 222A, or consent of instructor.').
course('CSE 223A',"Principles of Distributed Computing",exactly(4),"(Formerly CSE 223.) Logical and physical time, snapshot protocols, failure models, replication strategies, consensus and reliable broadcast, self-stabilization, atomic commit.",'CSE 221 or consent of instructor.').
course('CSE 223B',"Distributed Computing and Systems",exactly(4),"Efficient primitives for distributed operating systems and high-performance network servers, including concurrent and event-driven server architectures, remote procedure calls, and load shedding. Distributed naming, directory, and storage services, replication for fault tolerance, and security in distributed systems.",'CSE 221, CSE 222A, or consent of instructor.').
course('CSE 227',"Computer Security",exactly(4),"Security and threat models, risk analysis, authentication and authorization, auditing, operating systems security, access control mechanisms, protection mechanisms, distributed systems/network security, security architecture, electronic commerce security mechanisms, security evaluation.",'CSE 221 or consent of instructor.').
course('CSE 230',"Principles of Programming Languages",exactly(4),"(Formerly CSE 273.) Functional versus imperative programming. Type systems and polymorphism; the ML language. Higher order functions, lazy evaluation. Abstract versus concrete syntax, structural and well-founded induction. The lambda calculus, reduction strategies, combinators. Denotational semantics, elementary domain theory.",'CSE 130 or equivalent, or consent of instructor.').
course('CSE 231',"Advanced Compiler Design",exactly(4),"(Formerly CSE 264C.) Advanced material in programming languages and translator systems. Topics include compilers, code optimization, and debugging interpreters.",'CSE 100, 131A, or consent of instructor.').
course('CSE 232',"Principles of Database Systems",exactly(4),"(Formerly CSE 264D.) Database models including relational, hierarchic, and network approaches. Implementation of databases including query languages and system architectures.",'CSE 100 or consent of instructor.').
course('CSE 232B',"Database System Implementation",exactly(4),"A hands-on approach to the principles of databases implementation. Algebraic rewriters/optimizers, query processors, triggers. Beyond centralized relational databases.",'CSE 232.').
course('CSE 233',"Database Theory",exactly(4),"Theory of databases. Theory of query languages, dependency theory, deductive databases, incomplete information, complex objects, object-oriented databases, and more. Connections to logic and complexity theory including finite model theory and descriptive complexity.",'CSE 200.').
course('CSE 237A',"Introduction to Embedded Computing",exactly(4),"Embedded system technologies including processors, DSP, memory, and software. System interfacing basics, communication strategies, sensors, and actuators. Mobile and wireless technology in embedded systems. Using predesigned hardware and software components. Design case studies in wireless, multimedia, and/or networking domains.",'basic courses in digital hardware, algorithms and data structures, elementary calculus, and probability; or consent of instructor.').
course('CSE 237B',"Software for Embedded Systems",exactly(4),"Embedded computing elements, device interfaces, time-critical IO handling. Embedded software design under size, performance, and reliability constraints. Software timing and functional validation. Programming methods and compilation for embeddable software. Embedded runtime systems. Case studies of real-time software systems.",'CSE 237A; or basic courses in programming, algorithms and data structures, elementary calculus, discrete math, computer architecture; or consent of instructor.').
course('CSE 237C',"Validation and Testing of Embedded Systems",exactly(4),"Embedded system building blocks including IP cores. Cosimulation. Formal verification using model checking. Verification environments. Test challenges in core integration: compliance, feature, random, and collision testing. Core access and test integration. Interface-based verification and standards.",'CSE 237A; or basic courses in algorithms and data structures, elementary calculus, discrete math, symbolic logic, computer architecture; or consent of instructor.').
course('CSE 237D',"Design Automation and Prototyping for Embedded Systems",exactly(4),"System representation and modeling. Abstract and language models. Simulation as a modeling activity. Computational and hw/sw system prototypes. System analysis using models. Constraint and interface modeling. Behavioral compilation and synthesis.",'CSE 237A; or basic courses in digital logic design, algorithms and data structures, elementary calculus, discrete math, symbolic logic, computer architecture; or consent of instructor.').
course('CSE 240A',"Principles of Computer Architecture",exactly(4),"(Formerly CSE 240.) This course will cover fundamental concepts in computer architecture. Topics include instruction set architecture, pipelining, pipeline hazards, bypassing, dynamic scheduling, branch prediction, superscalar issue, memory-hierarchy design, advanced cache architectures, and multiprocessor architecture issues.",'CSE 141 or consent of instructor.').
course('CSE 240B',"Parallel Computer Architecture",exactly(4),"This course covers advanced topics in parallel computer architecture, including on-chip and off-chip interconnection networks, cache coherence, cache consistency, hardware multithreading, multi-core and tiled architectures. It incorporates the latest research and development on parallel architectures and compilation techniques for those architectures. CSE 240A recommended.",'graduate standing.').
course('CSE 240C',"Advanced Microarchitecture",exactly(4),"This course covers advanced topics in computer architecture. It incorporates the latest research and development on topics such as branch prediction, instruction-level parallelism, cache hierarchy design, speculative multithreading, reliable architectures, and power-management techniques. CSE 240A recommended.",'graduate standing.').
course('CSE 240D',"Application Specific Processors",exactly(4),"This course covers advanced topics in design concepts and implementation principles of application specific processors, including embedded system design principles and application specific processors, application specific instruction set processors, domain specific processor architectures, embedded memories and dynamically customizable processors. CSE 240A recommended.",'graduate standing.').
course('CSE 241A/ECE 260B',"VLSI Integration of Computing Circuitry",exactly(4),"VLSI integrated-circuit building blocks of computing systems, and their implementation. Computer-aided design and performance simulations, design exercises and projects. Devices, standard cells and interconnects, clocking, power/ground distribution, arithmetic modules, memories. Methodologies and tradeoffs in system implementation.",'layout (CSE 165 or ECE 260A) and logic design (CSE 140 or ECE 111), or consent of instructor.').
course('CSE 242A',"Integrated Circuit Layout Automation",exactly(4),"Couplings among timing, circuits and spatial embedding in nanometer-scale CMOS design. The role, and key problems, of physical layout in IC implementation. Example topics: RTL-to-GDSII methodologies, analyses and estimations, partitioning, floor planning, placement, routing, special net routing, cell generation, compaction.",'CSE 241A or consent of instructor.').
course('CSE 243A',"Introduction to Synthesis Methodologies in VLSI CAD",exactly(4),"Hardware software co-design, architectural level synthesis, control synthesis and optimization, scheduling, binding, register and bus sharing, interconnect design, module selection, combinational logic optimization, state minimization, state encoding, and retiming.",none).
course('CSE 244A',"VLSI Test",exactly(4),"Design for test, testing economics, defects, failures and faults, fault models, fault simulation, automatic test pattern generation, functional testing, memory, PLA, FPGA, microprocessor test, and fault diagnosis.",none).
course('CSE 245',"Computer Aided Circuit Simulation and Verification",exactly(4),"This course is about the computer algorithms, techniques, and theory used in the simulation and verification of electrical circuits.",'CSE 241A or consent of instructor.').
course('CSE 247',"Application Specific and Reconfigurable Computer Architecture",exactly(4),"This course covers architecture concepts used to tailor processors to a specific application or sets of applications. It covers Field-Programmable Gate Arrays (FPGAs), various forms of Application Specific Integrated Circuit (ASIC) designs, Application Specific Integrated Processors (ASIP), and augmenting customizable VHDL cores.",'CSE 241A or consent of instructor.').
course('CSE 248',"Algorithmic and Optimization Foundations for VLSI CAD",exactly(4),"Algorithmic techniques and optimization frameworks for large-scale, difficult optimizations. Primal-dual multicommodity flow approximations, approximations for geometric and graph Steiner formulations, continuous placement optimization, heuristics for Boolean satisfiability, multilevel methods, semidefinite programming, and application to other formulations (e.g., scheduling).",'CSE 241A or CSE 242A, or consent of instructor.').
course('CSE 250A',"Principles of Artificial Intelligence: Probabilistic Reasoning and Learning",exactly(4),"Methods based on probability theory for reasoning and learning under uncertainty. Content may include directed and undirected probabilistic graphical models, exact and approximate inference, latent variables, expectation-maximization, hidden Markov models, Markov decision processes, applications to vision, robotics, speech, and/or text. Recommended preparation: CSE 103 or similar course.",'graduate standing in CSE or consent of instructor.').
course('CSE 250B',"Principles of Artificial Intelligence: Learning Algorithms",exactly(4),"Algorithms for supervised and unsupervised learning from data. Content may include maximum likelihood; log-linear models, including logistic regression and conditional random fields; nearest neighbor methods; kernel methods; decision trees; ensemble methods; optimization algorithms; topic models; neural networks; and backpropagation. Recommended preparation: CSE 103 or similar course.",'graduate standing or consent of instructor.').
course('CSE 250C',"Machine Learning Theory",exactly(4),"Theoretical foundations of machine learning. Topics include concentration of measure, the PAC model, uniform convergence bounds, and VC dimension. Possible topics include online learning, learning with expert advice, multiarmed bandits, and boosting. Recommended preparation: CSE 103 and CSE 101 or similar course.",'graduate standing or consent of instructor.').
course('CSE 252A',"Computer Vision I",exactly(4),"Comprehensive introduction to computer vision providing broad coverage including low-level vision (image formation, photometry, color, image feature detection), inferring 3-D properties from images (shape-from shading, stereo vision, motion interpretation) and object recognition. Companion to CSE 252B covering complementary topics.",'Math 10D and Math 20A or equivalent.').
course('CSE 252B',"Computer Vision II",exactly(4),"Comprehensive introduction to computer vision providing focused coverage of multiview geometry, structure from motion, image segmentation, motion segmentation, texture analysis and recognition, object detection, and image-based rendering. Companion to CSE 252A covering complementary topics.",'Math 10D and Math 20A or equivalent.').
course('CSE 254',"Statistical Learning",exactly(4),"Learning algorithms based on statistics. Possible topics include minimum-variance unbiased estimators, maximum likelihood estimation, likelihood ratio tests, resampling methods, linear logistic regression, feature selection, regularization, dimensionality reduction, manifold detection. An upper-division undergraduate course on probability and statistics such as Math 183 or 186, or any graduate course on statistics, pattern recognition, or machine learning is recommended.",'graduate standing.').
course('CSE 255',"Data Mining and Predictive Analytics",exactly(4),"Learning methods for applications. Content may include data preparation, regression and classification algorithms, support vector machines, random forests, class imbalance, overfitting, decision theory, recommender systems and collaborative filtering, text mining, analyzing social networks and social media, protecting privacy, A/B testing. Recommended preparation: CSE 103 or similar.",'graduate standing or consent of instructor.').
course('CSE 256/LING 256',"Statistical Natural Language Processing",exactly(4),"Introduction to modern statistical approaches to natural language processing: part-of-speech tagging, word-sense disambiguation and parsing, using Markov models, hidden Markov models and probabilistic context-free grammars. Recommended: one of LIGN 165, LIGN 245, CSE 151, CSE 250A, CSE 254.",'graduate standing or consent of instructor.').
course('CSE 258A',"Cognitive Modeling",exactly(4),"Connectionist models and a sampling of other cognitive modeling techniques. Models of language processing, memory, sequential processes, and vision. Areas covered may vary depending on student and faculty interests. Can be repeated for credit. CSE 151 or CSE 250B or CSE 253 or CSE 254, or equivalent experience recommended.",'graduate standing.').
course('CSE 259',"Seminar in Artificial Intelligence",exactly(1),"A weekly meeting featuring local (and occasional external) speakers discussing their current research in Artificial Intelligence Neural Networks, and Genetic Algorithms. (S/U grades only.)",none).
course('CSE 260',"Parallel Computation",exactly(4),"(Formerly CSE 274A.) This course provides an overview of parallel hardware, algorithms, models, and software. Topics include Flynn taxonomy, interconnection networks, memory organization, a survey of commercially available multiprocessors, parallel algorithm paradigms and complexity criteria, parallel programming environments and tools for parallel debugging, language specification, mapping, performance, etc.",'graduate standing or consent of instructor.').
course('CSE 262',"System Support for Applications of Parallel Computation",exactly(4),"This course will explore design of software support for applications of parallel computation. Topics include: programming languages, run time support, portability, and load balancing. The course will terminate in a project.",'consent of instructor.').
course('CSE 272',"Advanced Image Synthesis",exactly(4),"Computer graphics techniques for creating realistic images. Topics include ray tracing, global illumination, subsurface scattering, and participating media. CSE 168 or equivalent recommended.",none).
course('CSE 280A',"Algorithms in Computational Biology",exactly(4),"(Formerly CSE 206B.) The course focuses on algorithmic aspects of modern bioinformatics and covers the following topics: computational gene hunting, sequencing, DNA arrays, sequence comparison, pattern discovery in DNA, genome rearrangements, molecular evolution, computational proteomics, and others.",'CSE 202 preferred or consent of instructor.').
course('CSE 282/BENG 202',"Bioinformatics II: Sequence and Structure Analysisethods and Applications",exactly(4),"(Formerly CSE 257A/BENG 202.) Introduction to methods for sequence analysis. Applications to genome and proteome sequences. Protein structure, sequence-structure analysis.",'Pharm 201 or consent of instructor.').
course('CSE 283/BENG 203',"Bioinformatics III: Functional Genomics",exactly(4),"Annotating genomes, characterizing functional genes, profiling, reconstructing pathways.",'Pharm 201, BENG 202/CSE 282, or consent of instructor.').
course('CSE 292',"Faculty Research Seminar",exactly(1),"(Formerly CSE 282.) Computer science and engineering faculty will present one-hour seminars of the current research work in their areas of interest.",'CSE graduate status.').
course('CSE 294',"Research Meeting in CSE",exactly(2),"Advanced study and analysis of active research in computer science and computer engineering. Discussion of current research and literature in the research specialty of the staff member teaching the course.",'consent of instructor.').
course('CSE 599',"Teaching Methods in Computer Science",exactly(2),"Training in teaching methods in the field of computer science. This course examines theoretical and practical communication and teaching techniques particularly appropriate to computer science.",'consent of faculty.').
major("AIP","Academic Internship Program").
major("ANAR","Anthropological Archeology").
major("ANBI","Anthropology/ Biological Anthropology").
major("ANES","Anesthesiology").
major("ANPR","Anthropology/ Program").
major("ANSC","Anthro/ Sociocultural Anthropology").
major("ANTH","Anthropology").
major("AUD","Audiology").
major("BENG","Bioengineering").
major("BGGN","Biology/ Grad/ General").
major("BGJC","Biology/ Grad/ Journal Club").
major("BGRD","Biology/ Grad/ Research Discussion").
major("BGSE","Biology/ Grad/ Seminar").
major("BIBC","Biology/ Biochemistry").
major("BICD","Biology/ Genetics, Cellular and Developmental").
major("BIEB","Biology/ Ecology, Behavior, and Evolutionary").
major("BILD","Biology/ Lower Division").
major("BIMM","Biology/ Molecular Biology, Microbiology").
major("BIOM","Biomedical Sciences").
major("BIPN","Biology/ Animal Physiology and Neuroscience").
major("BISP","Biology/ Special Studies").
major("CAT","Culture, Art, and Technology").
major("CBAP","Contemporary Black Arts Program").
major("CENG","Chemical Engineering").
major("CGS","Critical Gender Studies").
major("CHEM","Chemistry and Biochemistry").
major("CHIN","Chinese Studies").
major("CLAS","Classical Studies").
major("CLIN","Clinical Psychology").
major("CLRE","Clinical Research").
major("CLSS","Classics").
major("CMM","Cellular & Molecular Medicine").
major("COCU","Communication and Culture").
major("COGN","Communication/ General").
major("COGR","Communication/ Graduate").
major("COGS","Cognitive Science").
major("COHI","Communication/ Human Information Processing").
major("COMT","Communication Media Methods").
major("CONT","Contemporary Issues").
major("COSF","Communication as Social Force").
major("CSE","Computer Science and Engineering").
major("DOC","Dimensions of Culture").
major("EAP","Education Abroad Program").
major("ECE","Electrical and Computer Engineer").
major("ECON","Economics").
major("EDS","Education Studies").
major("ENG","Engineering").
major("ENVR","Environmental Studies").
major("ERC","Eleanor Roosevelt College").
major("ESYS","Environmental Systems").
major("ETHN","Ethnic Studies").
major("EXPR","Exchange Programs").
major("FILM","Film Studies").
major("FPM","Family and Preventive Medicine").
major("GMST","German Studies Program").
major("HDP","Human Development Program").
major("HEAL","Health Care ¨C Social Issues Program").
major("HIAF","History of Africa").
major("HIEA","History of East Asia").
major("HIEU","History of Europe").
major("HIGR","History, Graduate").
major("HILA","History of Latin America").
major("HILD","History, Lower Division").
major("HINE","History of the Near East").
major("HISC","History of Science").
major("HITO","History Topics").
major("HIUS","History of the United States").
major("HUM","Humanities").
major("ICAM","Computing and the Arts").
major("ICEP","Intercampus Exchange Program").
major("INTL","International Studies").
major("IRCO","International Relations/ Pacific Study-Core").
major("IRGN","International Relations/ Pac Study-General").
major("IRLA","International Relations/ Pacific Study-Language").
major("JAPN","Japanese Studies").
major("JUDA","Judaic Studies").
major("LANG","Language").
major("LATI","Latin American Studies").
major("LAWS","Law and Society").
major("LHCO","Leadership/ Health Care Organizations").
major("LIAB","Linguistics/ Arabic").
major("LIDS","Linguistics/ Directed Study-Language").
major("LIFR","Linguistics/ French").
major("LIGM","Linguistics/ German").
major("LIGN","Linguistics/ General").
major("LIHL","Linquistics/ Heritage Languages").
major("LIIT","Linguistics/ Italian").
major("LIPO","Linguistics/ Portuguese").
major("LISL","Linguistics/ American Sign Language").
major("LISP","Linguistics/ Spanish").
major("LTAF","Literature/ African").
major("LTAM","Literature of the Americas").
major("LTCO","Literature/ Comparative").
major("LTCS","Literature/ Cultural Studies").
major("LTEA","Literatures/ East Asian").
major("LTEN","Literatures in English").
major("LTEU","Literature/ European and Eurasian").
major("LTFR","Literature/ French").
major("LTGK","Literature/ Greek").
major("LTGM","Literature/ German").
major("LTHE","Literature/ Hebrew").
major("LTIT","Literature/ Italian").
major("LTKO","Literature/ Korean").
major("LTLA","Literature/ Latin").
major("LTNE","Literature/ Near Eastern").
major("LTRU","Literature/ Russian").
major("LTSP","Literature/ Spanish").
major("LTTH","Literature/ Theory").
major("LTWL","Literatures of the World").
major("LTWR","Literature/ Writing").
major("MAE","Mechanical and Aerospace Engineering").
major("MATH","Mathematics").
major("MATS","Materials Science and Engineering").
major("MBC","Marine Biodiversity & Conservation").
major("MCWP","Muir College Writing Program").
major("MED","Medicine").
major("MGT","Rady School of Management").
major("MMW","Making of the Modern World").
major("MSED","Mathematics and Science Education").
major("MSP","Muir Special Projects").
major("MUIR","Muir College").
major("MUS","Music").
major("NEU","Neurosciences").
major("OPTH","Ophthalmology").
major("ORTH","Orthopaedics").
major("PATH","Pathology").
major("PEDS","Pediatrics").
major("PHAR","Pharmacology").
major("PHIL","Philosophy").
major("PHYS","Physics").
major("POLI","Political Science").
major("PSY","Psychiatry").
major("PSYC","Psychology").
major("RAD","Radiology").
major("RELI","Religion, Study of").
major("REV","Revelle College").
major("RMED","Reproductive Medicine").
major("SDCC","San Diego Community College").
major("SE","Structural Engineering").
major("SIO","Scripps Inst of Oceanography").
major("SOCA","Sociology/ Theory and Methods").
major("SOCB","Sociology/ Culture, Language, and Social Interaction").
major("SOCC","Sociology/ Social Organization and Institutions").
major("SOCD","Sociology/ Comparative and Historical").
major("SOCE","Sociology/ Individual Research and Honors Project").
major("SOCG","Sociology/ Graduate").
major("SOCL","Sociology/ Lower Division").
major("SOMC","School of Medicine Core Courses").
major("SOMI","School of Medicine Interdisciplinary").
major("SPPS","Pharmacy").
major("STPA","Science, Technology and Public Affairs").
major("SURG","Surgery").
major("SXTH","Sixth College").
major("TDAC","Theatre/ Acting").
major("TDCH","Dance/ Choreography").
major("TDDE","Theatre/ Design").
major("TDDR","Theatre/ Directing and Stage Management").
major("TDGE","Theatre/ General").
major("TDGR","Theatre/ Graduate").
major("TDHD","Dance/ History").
major("TDHT","Theatre/ History & Theory").
major("TDMV","Dance/ Movement").
major("TDPF","Dance/ Performance").
major("TDPR","Theatre Dance/ Practicum").
major("TDPW","Theatre/ Playwriting").
major("TDTR","Dance/ Theory").
major("TMC","Thurgood Marshall College").
major("TWS","Third World Studies").
major("USP","Urban Studies and Planning").
major("VIS","Visual Arts").
major("WARR","Warren College").
major("WCWP","Warren College Writing Program").
